In [2]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.random.random(5)

array([0.49566979, 0.14786397, 0.65452997, 0.61806219, 0.68791458])

In [7]:
new_math = np.array([1, 2, 3])

In [8]:
new_ones = np.ones(3)

In [9]:
new_math + new_ones

array([2., 3., 4.])

In [10]:
new_math * 2

array([2, 4, 6])

In [11]:
new_ones * 3

array([3., 3., 3.])

In [12]:
new_math[0]

1

In [13]:
new_math[1]

2

In [14]:
new_math.max()

3

In [15]:
new_math.min()

1

In [16]:
new_math.sum()

6

In [19]:
x = np.array([[10, 20],[30, 40]])

In [20]:
x

array([[10, 20],
       [30, 40]])

In [22]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3, 4))

array([[0.5453538 , 0.0285257 , 0.44880308, 0.50447797],
       [0.93041945, 0.9237673 , 0.91420828, 0.08281697],
       [0.16828883, 0.9266791 , 0.1526515 , 0.70966777]])

In [25]:
y = np.array([[2, 4], [5, 6]])

In [26]:
x + y

array([[12, 24],
       [35, 46]])

In [27]:
x.dot(y)

array([[120, 160],
       [260, 360]])

In [28]:
y

array([[2, 4],
       [5, 6]])

In [29]:
y.max()

6

In [30]:
y.min()

2

In [31]:
y[0, 1]

4

In [32]:
y[1, 0]

5

In [33]:
y[0:2, 1]

array([4, 6])

In [39]:
new_data = np.array([1, 2, 3, 4, 5, 6])

In [40]:
new_data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
new_data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
x = np.array([[[10, 20], [3, 40]], [[50, 60], [70, 80]]])

In [4]:
x

array([[[10, 20],
        [ 3, 40]],

       [[50, 60],
        [70, 80]]])

In [5]:
np.ones((5, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
np.zeros((4, 5, 1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])